### ISSUE TITLE
Window icon does not appear

### ISSUE THREAD

**Issue by eltonfabricio10** [PhotoFlare/photoflare#255]
[ image photoflare window icon](https://drive.google.com/file/d/1IAAJ3EIvnr1qBwQlUUvHieWRmY4Eyyx2/view?usp=sharing)

**Comment by eltonfabricio10** [comment]
Operating system I'm using is based on Ubuntu Linux

**Comment by eltonfabricio10** [comment]
Try to build with that change...
[Commit](https://github.com/PhotoFlare/photoflare/commit/f9e4a3ab47b0f816e5905b71f2315290a5d6586b)

**Comment by DylanC** [comment]
@eltonfabricio10 - I will have a look at this later today. Thanks!

**Comment by DylanC** [comment]
@eltonfabricio10 - What OS is this?

**Comment by eltonfabricio10** [comment]
> @eltonfabricio10 - What OS is this?

Lubuntu 20.04

**Comment by DylanC** [comment]
@eltonfabricio10 - I ran the latest code on Lubuntu 20.04. We are missing the icon in the default icon theme. I can see we are on this list since we are new to Flathub:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2007

I have also created a request for this:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2129

**Comment by DylanC** [comment]
@eltonfabricio10 - The Papirus team have already put in a fix for this. https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2129

Not sure when that fix will be released but this has been actioned anyway.
